
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://izmgpyqiiuuoulbtjhxb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml6bWdweXFpaXV1b3VsYnRqaHhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY3MzA2OTksImV4cCI6MjA1MjMwNjY5OX0.twZha1kvvBGQ_wk9r-R8hCIz5vLWVY6CskIerFYx6sw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true
  }
});
